# Generated by Django 5.1.5 on 2025-01-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(max_length=255),
        ),
    ]
