# Generated by Django 5.1.5 on 2025-01-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_planta_fecha_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
