# Generated by Django 5.1.5 on 2025-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantas_usuario',
            name='descripcion_personalizada',
            field=models.TextField(default='A personalizar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantas_usuario',
            name='lugar',
            field=models.CharField(default='A personalizar', max_length=255),
            preserve_default=False,
        ),
    ]
