# Generated by Django 5.1.5 on 2025-01-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_plantas_usuario_descripcion_personalizada_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantas_usuario',
            unique_together={('planta', 'usuario')},
        ),
    ]
