# Generated by Django 5.1.5 on 2025-01-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_plantas_usuario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta_categoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_plantas', to='usuario.categoria'),
        ),
        migrations.AlterField(
            model_name='planta_categoria',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta_categorias', to='usuario.planta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
